try {
    {}.b;
} catch(e) {
    print("THE ERROR WAS:");
    print(e);
}